name: 'Build-Project-Go'
description: 'Build a Go project'
inputs:
  name:  # id of input
    description: 'Project name'
    required: true
  language: 
    required: true
    description: 'Project language'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Set up Go
      if: ${{ inputs.language == 'golang' }}
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Build
      shell: bash
      run: make build
