name: General CI Workflow

on:
  # push:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      project-src:
        required: false
        type: string
        default: "."
      language:
        required: true
        type: string
      release-binary:
        required: false
        type: boolean
      release-image:
        required: false
        type: boolean
      dockerhub-user:
        required: false
        type: string
    secrets:
      dockerhub-passwd:
        required: false

jobs:

  build-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out actions
        uses: actions/checkout@v2
        with:
          repository: saltbo/actions
          path: ./.github/actions
      - name: MakeTest
        uses: ./.github/actions/make-test
        with:
          language: ${{inputs.language}}

  release-binary:
    if: ${{inputs.release-binary}}
    runs-on: ubuntu-18.04
    needs: [build-test]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out actions
        uses: actions/checkout@v2
        with:
          repository: saltbo/actions
          path: ./.github/actions
      - name: Binary build and release
        uses: ./.github/actions/release-binary
        with:
          path: ${{inputs.project-src}}

  release-image:
    if: ${{inputs.release-image}}
    runs-on: ubuntu-18.04
    needs: [build-test]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out actions
        uses: actions/checkout@v2
        with:
          repository: saltbo/actions
          path: ./.github/actions
      - name: Image build and release
        uses: ./.github/actions/release-image
        with:
          context: ${{inputs.project-src}}
          language: ${{inputs.language}}
          username: ${{inputs.dockerhub-user}}
          password: ${{secrets.dockerhub-passwd}}
          tags: ${{inputs.dockerhub-user}}/${{inputs.project-name}}