name: General CI Workflow

on:
  # push:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      language:
        required: true
        type: string
      release-binary:
        required: false
        type: boolean
      release-docker-image:
        required: false
        type: boolean
    # secrets:
    #   token:
    #     required: true

jobs:

  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out actions
        uses: actions/checkout@v2
        with:
          repository: saltbo/actions
          path: ./.github/actions
      - name: MakeTest
        uses: ./.github/actions/unit-test
        with:
          language: ${{inputs.language}}

  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: [test]
    steps:
      - name: Check out actions
        uses: actions/checkout@v2
        with:
          repository: saltbo/actions
          path: ./.github/actions
      - name: Build binary
        uses: ./.github/actions/build-binary
        with:
          name: ${{inputs.project-name}}
          language: ${{inputs.language}}

  release-binary:
    if: ${{inputs.release-binary}}
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - name: Check out actions
        uses: actions/checkout@v2
        with:
          repository: saltbo/actions
          path: ./.github/actions
      - name: Release Binary
        uses: ./.github/actions/release-binary

  release-docker-image:
    if: ${{inputs.release-docker-image}}
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - name: Check out actions
        uses: actions/checkout@v2
        with:
          repository: saltbo/actions
          path: ./.github/actions
      - name: Release Docker Image
        uses: ./.github/actions/release-docker-image