name: GoProjectDemo

on:
  push:
  pull_request:
    
jobs:
  general-ci:
    uses: saltbo/actions/.github/workflows/general-ci.yml@master
    with:
      project-name: xxx
      language: golang
      release-binary: true
      release-image: true
    secrets:
      dockerhub-user: saltbo
      dockerhub-passwd: ${{ secrets.DOCKERHUB_PASSWD }}