name: General CI Workflow

on:
  # push:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      language:
        required: true
        type: string
      release-binary:
        required: false
        type: boolean
      release-image:
        required: false
        type: boolean
    secrets:
      dockerhub-user:
        required: true
      dockerhub-passwd:
        required: true

jobs:

  build-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out actions
        uses: actions/checkout@v2
        with:
          repository: saltbo/actions
          path: ./.github/actions
      - name: MakeTest
        uses: ./.github/actions/make-test
        with:
          language: ${{inputs.language}}

  release-binary:
    if: ${{inputs.release-binary}}
    runs-on: ubuntu-18.04
    needs: [build-test]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out actions
        uses: actions/checkout@v2
        with:
          repository: saltbo/actions
          path: ./.github/actions
      - name: Release Binary
        uses: ./.github/actions/release-binary

  release-image:
    if: ${{inputs.release-image}}
    runs-on: ubuntu-18.04
    needs: [build-test]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out actions
        uses: actions/checkout@v2
        with:
          repository: saltbo/actions
          path: ./.github/actions
      - name: Release Image
        uses: ./.github/actions/release-image
        with:
          tags: "saltbo/action-test"