name: General Go CI Action

on:
  push:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:

  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Unit tests.
        run: make test
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1
        with:
#          token: ${{secrets.CODECOV_TOKEN}}
          file: .coverprofile
  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: [test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: saltbo/actions
          path: .github/actions
      - name: build-project-go
        uses: ./.github/actions/.github/actions/build-project-go
        with:
          username: saltbo